from __future__ import annotations

DEFAULT_ANNOTATION = (
    "Data Source: Export Promotion Bureau, Bangladesh (https://epb.portal.gov.bd/)\n"
    "Analysis & Visualisation by: Abdul Aziz Pervez"
)

HS_CODE_MAP = {
    "01": "Live Animals",
    "02": "Meat",
    "03": "Fish & Crustaceans",
    "04": "Dairy & Eggs",
    "05": "Animal Origin Products",
    "06": "Live Trees & Plants",
    "07": "Edible Vegetables",
    "08": "Edible Fruits & Nuts",
    "09": "Coffee, Tea, & Spices",
    "10": "Cereals",
    "11": "Milling Products",
    "12": "Oil Seeds",
    "13": "Lac, Gums, Resins",
    "14": "Vegetable Plaiting Materials",
    "15": "Animal or Vegetable Fats",
    "16": "Meat/Fish Preparations",
    "17": "Sugars",
    "18": "Cocoa",
    "19": "Cereal Preparations",
    "20": "Vegetable/Fruit Preparations",
    "21": "Misc. Edible Preparations",
    "22": "Beverages & Spirits",
    "23": "Food Industries Residues",
    "24": "Tobacco",
    "25": "Salt, Sulphur, Earth",
    "26": "Ores, Slag, & Ash",
    "27": "Mineral Fuels & Oils",
    "28": "Inorganic Chemicals",
    "29": "Organic Chemicals",
    "30": "Pharmaceutical Products",
    "31": "Fertilizers",
    "32": "Tanning & Dyeing Extracts",
    "33": "Essential Oils",
    "34": "Soaps & Waxes",
    "35": "Albuminoidal Substances",
    "36": "Explosives",
    "37": "Photographic Goods",
    "38": "Misc. Chemical Products",
    "39": "Plastics",
    "40": "Rubber",
    "41": "Raw Hides & Skins",
    "42": "Leather Articles",
    "43": "Furskins",
    "44": "Wood",
    "45": "Cork",
    "46": "Straw Manufactures",
    "47": "Wood Pulp",
    "48": "Paper & Paperboard",
    "49": "Printed Books",
    "50": "Silk",
    "51": "Wool",
    "52": "Cotton",
    "53": "Other Vegetable Fibers",
    "54": "Man-made Filaments",
    "55": "Man-made Staple Fibers",
    "56": "Wadding, Felt, & Nonwovens",
    "57": "Carpets",
    "58": "Special Woven Fabrics",
    "59": "Impregnated/Coated Fabrics",
    "60": "Knitted or Crocheted Fabrics",
    "61": "Knitted Apparel",
    "62": "Woven Apparel",
    "63": "Other Made-up Textiles",
    "64": "Footwear",
    "65": "Headgear",
    "66": "Umbrellas & Canes",
    "67": "Prepared Feathers",
    "68": "Stone & Plaster Articles",
    "69": "Ceramic Products",
    "70": "Glass & Glassware",
    "71": "Precious Stones & Metals",
    "72": "Iron & Steel",
    "73": "Articles of Iron or Steel",
    "74": "Copper",
    "75": "Nickel",
    "76": "Aluminum",
    "78": "Lead",
    "79": "Zinc",
    "80": "Tin",
    "81": "Other Base Metals",
    "82": "Tools & Cutlery",
    "83": "Misc. Articles of Base Metal",
    "84": "Machinery",
    "85": "Electrical Machinery",
    "86": "Railway & Tramway",
    "87": "Vehicles",
    "88": "Aircraft & Spacecraft",
    "89": "Ships, Boats",
    "90": "Optical & Medical Instruments",
    "91": "Clocks & Watches",
    "92": "Musical Instruments",
    "93": "Arms & Ammunition",
    "94": "Furniture",
    "95": "Toys, Games, & Sports",
    "96": "Misc. Manufactured Articles",
    "97": "Works of Art",
    "98": "Special Classification",
    "99": "Special Classification",
}

# Emoji support is optional; values can be updated per project needs.
EMOJI_MAP: dict[str, str] = {}
